cmake_minimum_required(VERSION 3.25)

project(homework_2 C)

add_executable(counting_lucky_tickets counting_lucky_tickets.c)
add_executable(fast_polynomial_calculation fast_polynomial_calculation.c)
add_executable(flipping_the_array flipping_the_array.c)
add_executable(incomplete_quotient incomplete_quotient.c)


